name: Build and Release

jobs:
  - build-and-release:
      runs-on: ubuntu-latest

      steps:
        - name: Check out code
          uses: actions/checkout@v2
    
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.20
    
        - name: Build using makefile
          run: |
            make compile